// Game content: the event deck, ranks, perks and copy.
// Events move *market prices*, not opaque position blobs — so the ticker the
// player sees is the same number that drives their P&L. btc/sol/meme are
// fractional price deltas; apy/risk shift systemic yield and danger.

export const EVENTS = [
  {
    id: "etf-bid",
    title: "ETF bid returns",
    body: "Majors catch a steady institutional bid. Boring green candles are still green candles.",
    tone: "good",
    category: "macro",
    btc: 0.1,
    sol: 0.13,
    meme: 0.04,
    apy: -4,
    risk: -3,
  },
  {
    id: "meme-supercycle",
    title: "Meme supercycle thread",
    body: "A viral thread convinces the timeline that culture is the new fundamentals. Liquidity follows the joke.",
    tone: "good",
    category: "meme",
    btc: 0.02,
    sol: 0.05,
    meme: 1.3,
    apy: 2,
    risk: 12,
  },
  {
    id: "bridge-exploit",
    title: "Bridge exploit rumors",
    body: "Nobody knows which protocol is hit, so everyone sells first and researches later.",
    tone: "bad",
    category: "defi",
    btc: -0.06,
    sol: -0.1,
    meme: -0.22,
    apy: 9,
    risk: 18,
  },
  {
    id: "points-season",
    title: "DeFi points season",
    body: "Protocols throw points at anyone willing to click through twelve modals and call it strategy.",
    tone: "good",
    category: "defi",
    btc: 0.02,
    sol: 0.05,
    meme: -0.03,
    apy: 18,
    risk: 8,
  },
  {
    id: "macro-scare",
    title: "Macro scare",
    body: "Rates, liquidity and a chart with too many arrows all point the same ugly way for a few days.",
    tone: "bad",
    category: "macro",
    btc: -0.12,
    sol: -0.18,
    meme: -0.3,
    apy: 5,
    risk: 14,
  },
  {
    id: "influencer-wallet",
    title: "Influencer wallet spotted",
    body: "A famous wallet buys a microcap. Some call it alpha, others call it exit liquidity with better lighting.",
    tone: "good",
    category: "meme",
    btc: 0.01,
    sol: 0.03,
    meme: 0.9,
    apy: 1,
    risk: 14,
  },
  {
    id: "stable-wobble",
    title: "Stablecoin wobble",
    body: "A large pool trades off peg for an hour. The market remembers that stable does not mean magical.",
    tone: "bad",
    category: "defi",
    btc: -0.05,
    sol: -0.09,
    meme: -0.16,
    apy: 14,
    risk: 20,
  },
  {
    id: "builder-week",
    title: "Builder week",
    body: "A quiet week. Shipping and boring risk management quietly outperform the loudest screenshots.",
    tone: "neutral",
    category: "spot",
    btc: 0.04,
    sol: 0.05,
    meme: -0.02,
    apy: -2,
    risk: -8,
  },
  {
    id: "listing-leak",
    title: "Exchange listing leak",
    body: "A mid-cap gets listed and the rumor mill sprays sparks across every related token.",
    tone: "good",
    category: "spot",
    btc: 0.08,
    sol: 0.14,
    meme: 0.2,
    apy: 1,
    risk: 7,
  },
  {
    id: "rug-montage",
    title: "Rug pull montage",
    body: "Three tiny tokens vanish in one morning. The chart has a candle shape that should be illegal.",
    tone: "bad",
    category: "meme",
    btc: -0.02,
    sol: -0.04,
    meme: -0.62,
    apy: 6,
    risk: 16,
  },
  {
    id: "halving-narrative",
    title: "Halving narrative heats up",
    body: "Supply-shock charts go viral again. Half the replies are wrong, the trend is not.",
    tone: "good",
    category: "macro",
    btc: 0.14,
    sol: 0.1,
    meme: 0.06,
    apy: -3,
    risk: -4,
  },
  {
    id: "regulation",
    title: "Regulatory headline",
    body: "A government discovers crypto exists again. Lawyers bill, charts dump, nothing is clear.",
    tone: "bad",
    category: "macro",
    btc: -0.1,
    sol: -0.15,
    meme: -0.28,
    apy: 3,
    risk: 16,
  },
  {
    id: "airdrop-meta",
    title: "Airdrop farming meta",
    body: "Everyone is suddenly a power user of protocols they will never open again.",
    tone: "good",
    category: "defi",
    btc: 0.01,
    sol: 0.06,
    meme: 0.05,
    apy: 22,
    risk: 10,
  },
  {
    id: "sol-outage",
    title: "Network outage FUD",
    body: "A chain hiccups for a few hours. The timeline writes its obituary, then buys the dip.",
    tone: "bad",
    category: "spot",
    btc: -0.02,
    sol: -0.2,
    meme: -0.12,
    apy: 2,
    risk: 12,
  },
  {
    id: "meme-cex",
    title: "Memecoin hits a CEX",
    body: "A joke token gets a real listing. The chart goes vertical and so does everyone's pulse.",
    tone: "good",
    category: "meme",
    btc: 0.02,
    sol: 0.06,
    meme: 1.1,
    apy: 0,
    risk: 12,
  },
  {
    id: "quiet-accum",
    title: "Quiet accumulation",
    body: "Volume is dead, charts are flat, and the smart money is supposedly buying. Allegedly.",
    tone: "neutral",
    category: "spot",
    btc: 0.05,
    sol: 0.06,
    meme: 0.0,
    apy: -1,
    risk: -6,
  },
  {
    id: "leverage-flush",
    title: "Leverage flush",
    body: "A cascade of liquidations vaporizes the overconfident. Spot holders just watch the fireworks.",
    tone: "bad",
    category: "macro",
    btc: -0.15,
    sol: -0.22,
    meme: -0.4,
    apy: 6,
    risk: 18,
  },
  {
    id: "protocol-rev",
    title: "Protocol revenue ATH",
    body: "A blue-chip protocol prints real fees. For one week, fundamentals are briefly cool again.",
    tone: "good",
    category: "defi",
    btc: 0.03,
    sol: 0.08,
    meme: 0.02,
    apy: 12,
    risk: -2,
  },
  {
    id: "nft-spillover",
    title: "NFT mania spillover",
    body: "A new collection mints out in seconds and the hype leaks into every adjacent token.",
    tone: "good",
    category: "meme",
    btc: 0.02,
    sol: 0.1,
    meme: 0.7,
    apy: 1,
    risk: 10,
  },
  {
    id: "whale-distribution",
    title: "Whale distribution",
    body: "A wallet that bought the bottom starts handing bags to the people who arrived late.",
    tone: "bad",
    category: "spot",
    btc: -0.08,
    sol: -0.12,
    meme: -0.18,
    apy: 2,
    risk: 10,
  },
];

// Rotating memecoin identities. A fresh one spawns after each rug.
export const MEME_NAMES = [
  "DOGGO",
  "WIFCAP",
  "BONKLET",
  "MOONPUG",
  "GIGAFROG",
  "TURBO9000",
  "MOCHI",
  "SHIBLET",
  "PEPENODE",
  "CHADCOIN",
  "FOMO",
  "NORUG",
];

// Net-worth tiers. $1M is intentionally a rare stretch tier, not the expected
// outcome — most skilled risk-managed runs should land Climber..Alpha.
export const MILESTONES = [
  { id: "intern", name: "Wallet intern", at: 0 },
  { id: "survivor", name: "Market survivor", at: 1500 },
  { id: "climber", name: "Chain climber", at: 4000 },
  { id: "pm", name: "Portfolio manager", at: 10000 },
  { id: "alpha", name: "Alpha operator", at: 50000 },
  { id: "legend", name: "Cycle legend", at: 150000 },
  { id: "millionaire", name: "Crypto millionaire", at: 1_000_000 },
];

// Meta-progression perks. Unlocked by past performance, NOT bought.
// Daily mode ignores perks so the leaderboard stays fair.
export const PERKS = [
  {
    id: "research-desk",
    name: "Research Desk",
    desc: "Start every week with a sharper read on the incoming signal.",
    unlockAt: 25_000,
  },
  {
    id: "hardware-wallet",
    name: "Hardware Wallet",
    desc: "Begin runs with hardened security (+20).",
    unlockAt: 100_000,
  },
  {
    id: "steady-hands",
    name: "Steady Hands",
    desc: "Stress builds 30% slower under pressure.",
    unlockAt: 250_000,
  },
  {
    id: "seed-capital",
    name: "Seed Capital",
    desc: "A small earned head start: +$500 starting cash.",
    unlockAt: 500_000,
  },
];

// One concrete takeaway per cause of death — loss should teach, not just sting.
export const LESSONS = {
  rug: "Memecoins round-trip to zero. The exit is a decision you make on the way up, not after.",
  hack: "An unhardened wallet is a countdown. Security costs less than a drain.",
  macro: "Going all-in right before a macro flush is how good runs end early.",
  overexposed: "Concentration makes you rich slowly and broke instantly. Size your bets.",
  bear: "Cash is a position. Surviving the bear is half of winning the cycle.",
  burnout: "Stress is a position too. Rest weeks and selling pressure aren't weakness — they keep you in the game.",
  exile: "Reputation is the one thing that compounds across cycles. Chase rugs and the room stops taking your calls.",
  default: "Risk you cannot see is still risk. Read the signal before you commit.",
};

export const TUTORIAL = [
  "1 turn = 1 week of the market. You get 3 energy to act each week.",
  "Read the SIGNAL for next week. Spend energy on Research to sharpen a fuzzy read before you commit.",
  "Buy majors, ape a meme, farm DeFi yield — but watch the live RUG and HACK risk before pressing Next Week.",
  "Selling is free: taking profit is the whole game. Diamond hands and graveyards share an address.",
  "Reach the next rank. $1M is the legend tier — survival and smart sizing get you most of the way.",
];
